### ISSUE TITLE
Dependency "Easy-iOS-SDK" has no shared framework schemes

### ISSUE THREAD

**Issue by semiosisgit** [DIBS-Payment-Services/Easy-iOS-SDK#2]
![Screenshot 2020-08-26 at 6 15 40 PM](https://user-images.githubusercontent.com/58501283/91305118-2c3ea580-e7c8-11ea-815b-d2496a0efcdb.png)
Showing "Dependency "Easy-iOS-SDK" has no shared framework schemes" on carthage update

**Comment by semiosisgit** [comment]
![Screenshot 2020-08-26 at 6 24 10 PM](https://user-images.githubusercontent.com/58501283/91306392-0fa36d00-e7ca-11ea-9d2d-5c4684e87ff0.png)
While uploading app to app Store Showing error 
"Unsupported Architecture"

**Comment by Nets-in-app** [comment]
Hi,

Kindly check the Integration - Run Script section of the readme file for the distribution error.
