### ISSUE TITLE
Building for iOS Simulator, but the linked and embedded framework 'Mia.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by sameer4** [DIBS-Payment-Services/Easy-iOS-SDK#4]
Hi, I'm receiving this error in xCode 12.3(both running for simulator and in archiving the build)

**Building for iOS Simulator, but the linked and embedded framework 'Mia.framework' was built for iOS + iOS Simulator.**

let me know if you need more information

**Comment by Skovie** [comment]
Im getting the same error

**Comment by Nets-in-app** [comment]
Hi, We have observed this issue on Xcode 12.3 version and are investigating this. 

As a temporary fix, you can try the following.

Setting the `Validate Workspace` to `true` on the `Builds Settings` for the `Target` will change the Error to Warning.

**Comment by Nets-in-app** [comment]
Hi, We have added the new XCFramework which fixes this issue.
