### ISSUE TITLE
Disable Pay later and Split Payment Options

### ISSUE THREAD

**Issue by Maddumage** [DIBS-Payment-Services/Easy-iOS-SDK#5]
Hi,
I want to remove or disable the Pay later and Split payment option from the payment window. Is it possible to do?. Are there any UI customizations for this SDK?

**Comment by Tim-Badin** [comment]
Hi  @Maddumage ,

This is possible. To do it, kindly send a request to disable invoices (pay later / split) to your Easy account manager or our support department, together with the merchant ID.
In addition, UI customization is possible from the Easy portal. Kindly refer to the "checkout styler" in the administration dashboard https://portal.dibspayment.eu/dashboard

**Comment by Maddumage** [comment]
@Tim-Badin  Thank you very much for your support.
